services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5436:5432
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    image: app
    build: ./
    ports:
      - 8080:8000
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgrespw
      - DB_HOST=postgres
      - DB_P0RT=5432
      - DB_NAME=postgres
      - APP_HOST=app
      - APP_PORT=8000